In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("data.csv")
df

       pos_x  pscale
0   0.000000  0.0000
1   0.161389  0.0248
2   0.322778  0.0496
3   0.484167  0.0744
4   0.645556  0.0992
5   0.806944  0.1240
6   0.968333  0.1488
7   1.129722  0.1736
8   1.291111  0.1984
9   1.452500  0.2232
10  1.613889  0.2480
11  1.775278  0.2728
12  1.936667  0.2976
13  2.098056  0.3224
14  2.259444  0.3472
15  2.420833  0.3720
16  2.582222  0.3968
17  2.743611  0.4216
18  2.905000  0.4464

In [23]:
import numpy as np
from sklearn.linear_model import LinearRegression

# Prepare data
x_pos = np.arange(len(df)).reshape(-1, 1)  # Now reshape the array, not the integer
y_pos = df['pos_x'].values                 # y values

# Create and train model
model_pos = LinearRegression()
model_pos.fit(x_pos, y_pos )
next_pos_x = model_pos.predict([[len(df)]])[0]

In [49]:
import pickle
# Create and train model
model_pos = LinearRegression()
model_pos.fit(x_pos, y_pos )
next_pos_x = model_pos.predict([[len(df)]])[0]

with open("mode_pos.pk1","wb") as f:
  pickle.dump(model_pos,f)

In [24]:
next_pos_x

np.float64(3.0663888812587974)

In [25]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

poly = PolynomialFeatures(degree=3)
x_pscale = poly.fit_transform(np.arange(len(df)).reshape(-1,1))
y_pscale = df['pscale'].values

model_pscale = LinearRegression()
model_pscale.fit(x_pscale, y_pscale)
next_pscale = model_pscale.predict(poly.transform([[len(df)]]))[0]

In [26]:
next_pscale

np.float64(0.4711999829178174)

In [28]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
from sklearn.preprocessing import MinMaxScaler

In [29]:
df.head()

      pos_x  pscale
0  0.000000  0.0000
1  0.161389  0.0248
2  0.322778  0.0496
3  0.484167  0.0744
4  0.645556  0.0992

In [32]:
scaler = MinMaxScaler()
scaled = scaler.fit_transform(df)

scaled

array([[0.        , 0.        ],
       [0.05555556, 0.05555555],
       [0.11111111, 0.11111111],
       [0.16666666, 0.16666666],
       [0.22222222, 0.22222222],
       [0.27777778, 0.27777778],
       [0.33333333, 0.33333331],
       [0.3888889 , 0.38888887],
       [0.44444445, 0.44444444],
       [0.5       , 0.5       ],
       [0.55555555, 0.55555556],
       [0.6111111 , 0.61111113],
       [0.66666665, 0.66666662],
       [0.72222225, 0.72222225],
       [0.7777778 , 0.77777775],
       [0.83333335, 0.83333338],
       [0.8888889 , 0.88888887],
       [0.94444445, 0.94444444],
       [1.        , 1.        ]])

In [34]:
def create_sequences(data, seq_length):
  x, y = [], []
  for i in range(len(data) - seq_length):
    x.append(data[i:(i + seq_length)])
    y.append(data[i + seq_length])
  return np.array(x), np.array(y)

In [35]:
sequence_length = 3
x,y = create_sequences(scaled, sequence_length)

In [40]:
#buidling LSTM model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM

#model
model = Sequential()
model.add(LSTM(50, activation= 'relu', input_shape=(x.shape[1], x.shape[2])))
model.add(Dense(2))

#compile
model.compile(optimizer = 'adam', loss ='mse')

In [42]:
#train the model
model.fit(x,y , epochs =200, verbose=1)

Epoch 1/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 0.4311
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 0.4247
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - loss: 0.4185
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.4123
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.4062
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.4003
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.3946
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.3890
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.3834
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.3780
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.3726
Epoch 12/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.3672
Epoch 13/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.3618
Epoch 14/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.3565
Epoch 15/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.3511
Epoch 16/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.3458
Epoch 17/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.3404
Epoch 18/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - loss: 0.3350
Epoch 19/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.3296
Epoch 20/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.3241
Epoch 21/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.3187
Epoch 22/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.3132
Epoch 23/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.3078
Epoch 24/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.3024
Epoch 25/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 0.2968
Epoch 26/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.2912
Epoch 27/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.2856
Epoch 28/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.2798
Epoch 29/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.2740
Epoch 30/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.2681
Epoch 31/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.2622
Epoch 32/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.2561
Epoch 33/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.2499
Epoch 34/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 0.2437
Epoch 35/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.2373
Epoch 36/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.2309
Epoch 37/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.2244
Epoch 38/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.2178
Epoch 39/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.2112
Epoch 40/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.2044
Epoch 41/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.1976
Epoch 42/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.1908
Epoch 43/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.1838
Epoch 44/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.1768
Epoch 45/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.1697
Epoch 46/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.1626
Epoch 47/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.1553
Epoch 48/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.1479
Epoch 49/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.1405
Epoch 50/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.1331
Epoch 51/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 0.1256
Epoch 52/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.1180
Epoch 53/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.1104
Epoch 54/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.1029
Epoch 55/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 0.0954
Epoch 56/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0879
Epoch 57/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.0805
Epoch 58/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.0733
Epoch 59/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.0661
Epoch 60/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 0.0592
Epoch 61/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.0524
Epoch 62/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.0459
Epoch 63/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.0397
Epoch 64/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.0338
Epoch 65/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.0284
Epoch 66/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.0233
Epoch 67/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.0187
Epoch 68/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.0146
Epoch 69/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - loss: 0.0110
Epoch 70/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.0080
Epoch 71/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.0055
Epoch 72/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.0037
Epoch 73/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 0.0024
Epoch 74/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.0016
Epoch 75/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.0013
Epoch 76/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.0014
Epoch 77/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0018
Epoch 78/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.0024
Epoch 79/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.0032
Epoch 80/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0039
Epoch 81/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.0046
Epoch 82/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.0051
Epoch 83/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.0054
Epoch 84/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 0.0055
Epoch 85/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0054
Epoch 86/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.0051
Epoch 87/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.0048
Epoch 88/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0043
Epoch 89/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.0038
Epoch 90/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.0033
Epoch 91/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.0028
Epoch 92/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.0024
Epoch 93/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.0020
Epoch 94/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.0017
Epoch 95/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.0015
Epoch 96/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.0014
Epoch 97/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0013
Epoch 98/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.0012
Epoch 99/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.0012
Epoch 100/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.0013
Epoch 101/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 0.0013
Epoch 102/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - loss: 0.0014
Epoch 103/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0014
Epoch 104/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.0015
Epoch 105/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.0015
Epoch 106/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.0015
Epoch 107/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 0.0015
Epoch 108/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.0015
Epoch 109/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 0.0015
Epoch 110/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.0015
Epoch 111/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.0015
Epoch 112/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.0014
Epoch 113/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.0014
Epoch 114/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.0013
Epoch 115/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.0013
Epoch 116/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.0012
Epoch 117/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 0.0012
Epoch 118/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - loss: 0.0012
Epoch 119/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - loss: 0.0011
Epoch 120/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 0.0011
Epoch 121/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - loss: 0.0011
Epoch 122/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - loss: 0.0011
Epoch 123/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - loss: 0.0011
Epoch 124/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 0.0011
Epoch 125/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - loss: 0.0011
Epoch 126/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - loss: 0.0011
Epoch 127/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - loss: 0.0011
Epoch 128/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - loss: 0.0011
Epoch 129/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - loss: 0.0011
Epoch 130/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - loss: 0.0011
Epoch 131/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - loss: 0.0011
Epoch 132/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - loss: 0.0011
Epoch 133/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.0011
Epoch 134/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - loss: 0.0011
Epoch 135/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - loss: 0.0011
Epoch 136/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - loss: 0.0011
Epoch 137/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - loss: 0.0010
Epoch 138/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - loss: 0.0010
Epoch 139/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - loss: 0.0010
Epoch 140/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.0010
Epoch 141/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.0010
Epoch 142/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.0010
Epoch 143/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 0.0010
Epoch 144/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 9.9742e-04
Epoch 145/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 9.9299e-04
Epoch 146/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 9.8891e-04
Epoch 147/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 9.8504e-04
Epoch 148/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 9.8130e-04
Epoch 149/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 9.7757e-04
Epoch 150/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 9.7378e-04
Epoch 151/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 9.6990e-04
Epoch 152/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 9.6589e-04
Epoch 153/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 9.6175e-04
Epoch 154/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 9.5750e-04
Epoch 155/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - loss: 9.5315e-04
Epoch 156/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 9.4874e-04
Epoch 157/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 9.4432e-04
Epoch 158/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 9.3990e-04
Epoch 159/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 9.3554e-04
Epoch 160/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 9.3126e-04
Epoch 161/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 9.2707e-04
Epoch 162/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - loss: 9.2299e-04
Epoch 163/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 9.1903e-04
Epoch 164/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 9.1518e-04
Epoch 165/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 9.1143e-04
Epoch 166/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 9.0776e-04
Epoch 167/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 9.0417e-04
Epoch 168/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 9.0063e-04
Epoch 169/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 8.9713e-04
Epoch 170/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 8.9367e-04
Epoch 171/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 8.9022e-04
Epoch 172/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 8.8678e-04
Epoch 173/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - loss: 8.8335e-04
Epoch 174/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 8.7992e-04
Epoch 175/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 8.7649e-04
Epoch 176/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 8.7307e-04
Epoch 177/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 8.6966e-04
Epoch 178/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 8.6627e-04
Epoch 179/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 8.6289e-04
Epoch 180/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 8.5952e-04
Epoch 181/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 8.5618e-04
Epoch 182/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 8.5287e-04
Epoch 183/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 8.4958e-04
Epoch 184/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 8.4631e-04
Epoch 185/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - loss: 8.4306e-04
Epoch 186/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 8.3981e-04
Epoch 187/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 8.3657e-04
Epoch 188/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 8.3332e-04
Epoch 189/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 8.3006e-04
Epoch 190/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 8.2679e-04
Epoch 191/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - loss: 8.2350e-04
Epoch 192/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 8.2021e-04
Epoch 193/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 8.1691e-04
Epoch 194/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 8.1360e-04
Epoch 195/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 8.1030e-04
Epoch 196/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 8.0698e-04
Epoch 197/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 8.0369e-04
Epoch 198/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 8.0039e-04
Epoch 199/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 7.9710e-04
Epoch 200/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 7.9382e-04

In [43]:
last_seq = x[-1:]
predicted = model.predict(last_seq)

predicted_original_scale = scaler.inverse_transform(predicted)
print("Predicted next position:",predicted_original_scale[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 474ms/step
Predicted next position: [2.9743247  0.45784846]

In [44]:
df

       pos_x  pscale
0   0.000000  0.0000
1   0.161389  0.0248
2   0.322778  0.0496
3   0.484167  0.0744
4   0.645556  0.0992
5   0.806944  0.1240
6   0.968333  0.1488
7   1.129722  0.1736
8   1.291111  0.1984
9   1.452500  0.2232
10  1.613889  0.2480
11  1.775278  0.2728
12  1.936667  0.2976
13  2.098056  0.3224
14  2.259444  0.3472
15  2.420833  0.3720
16  2.582222  0.3968
17  2.743611  0.4216
18  2.905000  0.4464

In [48]:
# recursive predication
num_predictions = 5
predictions = []

last_seq = x[-1:]

for _ in range(num_predictions):
  predicted = model.predict(last_seq)
  predictions.append(predicted[0])
  predicted_reshaped = predicted.reshape(1,1,2)
  last_seq = np.concatenate((last_seq[:,1:,:], predicted_reshaped), axis=1)

predicted = scaler.inverse_transform(predictions)
print("Predictions:", predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step
Predictions: [array([1.0238639, 1.0256462], dtype=float32), array([1.1047021, 1.1080929], dtype=float32), array([1.2013535, 1.2064271], dtype=float32), array([1.3243384, 1.3319473], dtype=float32), array([1.4736185, 1.4849658], dtype=float32)]